# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f9e555478146c0de8516cb45154dd682596c7020b2f61c14707038474929830d23e7d903be47efa974dcc3eea4736f3b40d43f9de760eb3621e0f7a2a409d7

test:
  secret_key_base: b737504b7d7ba3bf424b1757d674fae9d38eb47e709267fa82e7e5230f93ceb808988cd7d3ac82cd947cc7be47be2236e7680e1e991bd3002620dc75881425ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
